version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./djangopr/:/usr/src/app/
    ports:
     - 8000:8000
    env_file:
     - ./.env.dev
  db:
    image: postgres:15.2
    container_name: postgresdj
    restart: always
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: post
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    ports:
     - '5432:5432'
volumes:
 postgres_data: