version: '3.1'

services:
  db:
    image: postgres
    container_name: postgresdj
    restart: always
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: post
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    ports:
     - '5432:5432'
volumes:
 postgres_data: