version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./djangopr/:/usr/src/app/
    ports:
     - 8000:8000
    env_file:
     - ./.env
  db:
    image: postgres:15.2
    container_name: postgresdj
    restart: always
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: post
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    ports:
     - '5432:5432'
  celery:
    build: .
    container_name: cl01
    command: celery -A server worker -l info
    depends_on:
        - redis
volumes:
 postgres_data: