FROM python:3.10-alpine
WORKDIR /usr/src/app

COPY ./entrypoint.prod.sh .
RUN chmod 777 entrypoint.prod.sh
RUN sed -i 's/\r$//g'  /usr/src/app/entrypoint.prod.sh
RUN chmod +x  /usr/src/app/entrypoint.prod.sh


COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIPENV_VENV_IN_PROJECT=1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install pipenv
RUN pipenv sync --system

ENTRYPOINT [" /usr/src/app/entrypoint.prod.sh"]