version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - db
      - redis

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=usercar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cars
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
 postgres_data: