version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=usercar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cars
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/usr/src/app/
    ports:
     - 8000:8000
    env_file:
     - ./.env
    depends_on:
      - db

volumes:
 postgres_data:
